name: Execute PowerShell Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  execute_powershell:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute PowerShell script
      shell: powershell
      run: |
        # Set execution policy to allow running scripts
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        $scriptDir = $PSScriptRoot
        write-host $scriptDir
        # Path to your PowerShell script in the repository
        $scriptPath = "C:\temp\test\hello.ps1"
    
        # Execute the PowerShell script
        & $scriptPath
