name: Execute PowerShell Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  execute_powershell:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute PowerShell script
      shell: powershell
      run: |
        # Set execution policy to allow running scripts
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        $scriptDir = $PSScriptRoot
        #write-host $scriptDir
        $test_val = "${{ vars.TEST }}"
        $sec_val = "${{secrets.TESTSEC}}"
        write-host "var Values is  : $test_val"
        # Path to your PowerShell script in the repository
        & .\hello.ps1 -test $test_val -TESTSEC $sec_val
    
        # Execute the PowerShell script
        #& $scriptPath
